name: semantic-release

on:
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: semantic release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_PREVIEW_GITHUB_TOKEN }}
